---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: postgres
    namespace: default
    labels:
      app: postgres
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgres
    template:
      metadata:
        namespace: default
        labels:
          app: postgres
      spec:
        containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "rootpassword"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432