apiVersion: v1
kind: Secret
metadata:
  namespace: vault
  name: vault-token-g955r
  annotations:
    kubernetes.io/service-account.name: vault
type: kubernetes.io/service-account-token
# This is needed to add a token+cert to vault SA